labs14-sauti-android/sauti-android

Sauti/.idea/misc.xml, Sauti/app/build.gradle, Sauti/app/src/main/AndroidManifest.xml, Sauti/app/src/main/java/com/sauti/sauti/MainActivity.kt, Sauti/app/src/main/res/drawable/half_star.xml, Sauti/app/src/main/res/drawable/side_nav_bar.xml, Sauti/app/src/main/res/layout/activity_main.xml, Sauti/app/src/main/res/layout/app_bar_main.xml, Sauti/app/src/main/res/layout/content_main.xml, Sauti/app/src/main/res/layout/nav_header_main.xml, Sauti/app/src/main/res/menu/activity_main_drawer.xml, Sauti/app/src/main/res/menu/main.xml, Sauti/app/src/main/res/values/dimens.xml, Sauti/app/src/main/res/values/strings.xml, Sauti/app/src/main/res/values/styles.xml
=> Navigation drawer

Sauti/.idea/misc.xml, Sauti/app/build.gradle, Sauti/app/src/main/AndroidManifest.xml, Sauti/app/src/main/java/com/sauti/sauti/activity/LanguageActivity.kt, Sauti/app/src/main/res/layout/activity_language.xml, Sauti/app/src/main/res/values/languages_array.xml, Sauti/app/src/main/res/values/strings.xml
=> Language activity

Sauti/app/src/main/AndroidManifest.xml, Sauti/app/src/main/java/com/sauti/sauti/activity/LanguageActivity.kt, Sauti/app/src/main/java/com/sauti/sauti/activity/MainActivity.kt, Sauti/app/src/main/java/com/sauti/sauti/activity/SearchActivity.kt, Sauti/app/src/main/java/com/sauti/sauti/sp/SessionSp.kt, Sauti/app/src/main/res/layout/activity_language.xml, Sauti/app/src/main/res/layout/nav_header_main.xml, Sauti/app/src/main/res/menu/activity_main_drawer.xml, Sauti/app/src/main/res/values/colors.xml, Sauti/app/src/main/res/values/strings.xml
=> better app flow

Sauti/.idea/misc.xml, Sauti/app/build.gradle, Sauti/app/src/main/java/com/labs/sauti/model/Product.kt, Sauti/app/src/main/java/com/labs/sauti/model/SautiApiError.kt, Sauti/app/src/main/java/com/labs/sauti/repository/RoomBaseDAO.kt, Sauti/build.gradle
=> Room Implementation

Sauti/app/src/main/java/com/labs/sauti/db/ProductDao.kt, Sauti/app/src/main/java/com/labs/sauti/db/ProductRepository.kt, Sauti/app/src/main/java/com/labs/sauti/db/RoomBaseDAO.kt, Sauti/app/src/main/java/com/labs/sauti/db/SautiRoomDatabase.kt, Sauti/app/src/main/java/com/labs/sauti/model/Product.kt
=> Added DAO, Repo, BaseDAO and SautiRoomDatabase

Sauti/app/build.gradle, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceSearchFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/SignInFragment.kt, Sauti/app/src/main/res/layout/fragment_sign_in.xml
=> reverted library versions

Sauti/app/src/main/java/com/labs/sauti/db/ProductDao.kt, Sauti/app/src/main/java/com/labs/sauti/db/ProductRepository.kt, Sauti/app/src/main/java/com/labs/sauti/db/SautiRoomDatabase.kt, Sauti/app/src/main/java/com/labs/sauti/db/TradeInfoDao.kt, Sauti/app/src/main/java/com/labs/sauti/db/TradeInfoRepository.kt, Sauti/app/src/main/java/com/labs/sauti/model/ProductData.kt, Sauti/app/src/main/java/com/labs/sauti/model/TradeInfoData.kt
=> Room cleanup

Sauti/.idea/misc.xml, Sauti/app/src/main/java/com/labs/sauti/activity/MarketPricesActivity.kt, Sauti/app/src/main/java/com/labs/sauti/cache/MarketPriceCache.kt, Sauti/app/src/main/java/com/labs/sauti/cache/MarketPriceRoomCache.kt, Sauti/app/src/main/java/com/labs/sauti/cache/RecentMarketPriceCache.kt, Sauti/app/src/main/java/com/labs/sauti/cache/RecentMarketPriceRoomCache.kt, Sauti/app/src/main/java/com/labs/sauti/db/MarketPriceDao.kt, Sauti/app/src/main/java/com/labs/sauti/db/RecentMarketPriceDao.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SautiRepositoryImpl.kt
=> Market price proper rxjava

Sauti/app/src/main/java/com/labs/sauti/activity/BaseActivity.kt, Sauti/app/src/main/java/com/labs/sauti/activity/TradeInfoActivity.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/DashboardFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRatesFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/HelpFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPricesFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketplaceFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/ReportFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TaxCalculatorFragment.kt, Sauti/app/src/main/res/layout/activity_trade_info.xml, Sauti/app/src/main/res/layout/app_bar_base.xml, Sauti/app/src/main/res/layout/content_base.xml, Sauti/app/src/main/res/layout/content_dashboard.xml, Sauti/app/src/main/res/layout/fragment_dashboard.xml, Sauti/app/src/main/res/layout/fragment_exchange_rates.xml, Sauti/app/src/main/res/layout/fragment_help.xml, Sauti/app/src/main/res/layout/fragment_market_prices.xml, Sauti/app/src/main/res/layout/fragment_marketplace.xml, Sauti/app/src/main/res/layout/fragment_report.xml, Sauti/app/src/main/res/layout/fragment_tax_calculator.xml, Sauti/app/src/main/res/values/colors.xml, Sauti/app/src/main/res/values/dimens.xml, Sauti/app/src/main/res/values/strings.xml
=> Single act multi frag conversion

Sauti/app/src/main/java/com/labs/sauti/cache/RecentMarketPriceSearchRoomCache.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceSearchFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TaxCalculatorFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TaxCalculatorSearchFragment.kt, Sauti/app/src/main/java/com/labs/sauti/model/RecentTaxCalculationSearchData.kt, Sauti/app/src/main/java/com/labs/sauti/model/TaxCalculationData.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SautiRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/sp/RecentMarketPricesSp.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/TaxCalculatorViewModel.kt, Sauti/app/src/main/res/layout/fragment_help.xml, Sauti/app/src/main/res/layout/fragment_market_price.xml, Sauti/app/src/main/res/layout/fragment_market_price_search.xml, Sauti/app/src/main/res/layout/fragment_report.xml, Sauti/app/src/main/res/layout/fragment_tax_calculator.xml, Sauti/app/src/main/res/layout/fragment_tax_calculator_search.xml, Sauti/app/src/main/res/layout/item_recent_market_price.xml, Sauti/app/src/main/res/layout/item_tax_calculation.xml, Sauti/app/src/main/res/layout/tool_app_bar_help.xml, Sauti/app/src/main/res/layout/tool_app_bar_report.xml, Sauti/app/src/main/res/layout/tool_app_bar_tax_calculator.xml, Sauti/app/src/main/res/values/colors.xml
=> TaxCalculator logic and Layout colors

Sauti/app/src/main/java/com/labs/sauti/fragment/BaseFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TradeInfoFragment.kt, Sauti/app/src/main/res/layout/fragment_trade_info.xml
=> Trade info layout bug fix

Sauti/app/build.gradle
=> To be pushed to google play console - testing track.

Sauti/app/src/main/java/com/labs/sauti/SautiApp.kt, Sauti/app/src/main/java/com/labs/sauti/activity/BaseActivity.kt, Sauti/app/src/main/java/com/labs/sauti/api/SautiApiService.kt, Sauti/app/src/main/java/com/labs/sauti/di/component/AuthenticationComponent.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/NetworkModule.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/SignInFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/SignUpFragment.kt, Sauti/app/src/main/java/com/labs/sauti/model/SignInResponse.kt, Sauti/app/src/main/java/com/labs/sauti/model/SignUpRequest.kt, Sauti/app/src/main/java/com/labs/sauti/model/SignUpResponse.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SautiRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SautiRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/sp/SessionSp.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/AuthenticationViewModel.kt, Sauti/app/src/main/res/layout/fragment_sign_up.xml, Sauti/app/src/main/res/values/colors.xml, Sauti/app/src/main/res/values/strings.xml
=> Authentication

Sauti/app/src/main/java/com/labs/sauti/db/SautiRoomDatabase.kt, Sauti/app/src/main/res/values/strings.xml, Sauti/app/src/main/res/values/styles.xml
=> Compilable and runnable

Sauti/app/src/main/java/com/labs/sauti/fragment/TaxCalculatorFragment.kt, Sauti/app/src/main/res/layout/fragment_tax_calculator.xml, Sauti/app/src/main/res/layout/fragment_tax_calculator_search.xml, Sauti/app/src/main/res/values/strings.xml
=> TaxCalculator layout polishing

Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt, Sauti/app/src/main/res/layout/fragment_market_price.xml, Sauti/app/src/main/res/layout/fragment_market_price_search.xml
=> MarketPrice scroll view

Sauti/app/src/main/java/com/labs/sauti/activity/BaseActivity.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/DashboardFragment.kt, Sauti/app/src/main/res/layout/fragment_dashboard.xml
=> Dashboard navigation

Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt
=> MarketPrice details animation

Sauti/app/src/main/res/layout/fragment_dashboard.xml
=> Rearranged nav card to mp, ti, er, tc

Sauti/app/src/main/res/menu/activity_main_drawer.xml
=> Rearranged nav drawer to mp, ti, er, tc

Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceSearchFragment.kt, Sauti/app/src/main/java/com/labs/sauti/helper/NetworkHelper.kt, Sauti/app/src/main/res/layout/fragment_market_price.xml, Sauti/app/src/main/res/layout/fragment_market_price_search.xml, Sauti/app/src/main/res/layout/item_recent_market_price.xml, Sauti/app/src/main/res/values/colors.xml
=> Market price polishing

Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRateFragment.kt
=> details visibility after convert

Sauti/app/src/main/java/com/labs/sauti/views/CardViewRecentSearches.kt, Sauti/app/src/main/res/layout/item_recent_card_view.xml, Sauti/app/src/main/res/values/styles.xml
=> Cardfix. Removed scroll

Sauti/app/src/main/res/layout/fragment_dashboard.xml
=> remove empty space for now

Sauti/app/src/main/java/com/labs/sauti/activity/BaseActivity.kt, Sauti/app/src/main/res/layout/nav_header_main.xml, Sauti/app/src/main/res/menu/activity_main_drawer.xml, Sauti/app/src/main/res/values/strings.xml
=> Removed authentication ui

Sauti/app/src/main/res/layout/fragment_marketplace.xml, Sauti/app/src/main/res/layout/tool_app_bar_marketplace.xml, Sauti/app/src/main/res/values/strings.xml
=> coming soon

Sauti/app/src/main/res/layout/fragment_settings.xml
=> Hide non functional ui

Sauti/app/src/main/java/com/labs/sauti/di/module/DataModule.kt, Sauti/app/src/main/res/values/colors.xml
=> compilable

Sauti/app/src/main/java/com/labs/sauti/db/SautiRoomDatabase.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TradeInfoFragment.kt, Sauti/app/src/main/java/com/labs/sauti/views/CardViewRecentSearches.kt, Sauti/app/src/main/res/layout/fragment_trade_info.xml
=> Added animations for presentation.

Sauti/app/src/main/java/com/labs/sauti/api/SautiApiService.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TaxCalculatorSearchFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TradeInfoFragment.kt, Sauti/app/src/main/java/com/labs/sauti/views/SearchSpinnerCustomView.kt
=> Added api requests. 

Sauti/app/src/main/java/com/labs/sauti/di/module/AuthenticationModule.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/DataModule.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/ExchangeRateModule.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/MarketPriceModule.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/SettingsModule.kt, Sauti/app/src/main/java/com/labs/sauti/repository/ExchangeRateRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/ExchangeRateRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/repository/MarketPriceRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/MarketPriceRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SautiRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SautiRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SettingsRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/SettingsRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/repository/UserRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/UserRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/AuthenticationViewModel.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/ExchangeRateViewModel.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/MarketPriceViewModel.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/SettingsViewModel.kt
=> System design

Sauti/app/src/main/java/com/labs/sauti/db/SautiRoomDatabase.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt, Sauti/app/src/main/java/com/labs/sauti/model/market_price/MarketPrice.kt, Sauti/app/src/main/java/com/labs/sauti/model/market_price/MarketPriceData.kt, Sauti/app/src/main/res/layout/fragment_market_price.xml, Sauti/app/src/main/res/layout/item_recent_market_price.xml
=> Market price

Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRateFragment.kt, Sauti/app/src/main/res/drawable/s_exchange_rate_result_border.xml, Sauti/app/src/main/res/layout/fragment_exchange_rate.xml
=> Exchange rate

Sauti/app/src/main/res/layout/fragment_dashboard.xml, Sauti/app/src/main/res/menu/activity_main_drawer.xml
=> rearrange menu to MP, ER, TI, TC

Sauti/app/src/main/java/com/labs/sauti/fragment/ReportFragment.kt, Sauti/app/src/main/java/com/labs/sauti/repository/ReportRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/ReportRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/ReportViewModel.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/report/BordersViewState.kt
=> border names listed

Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt
=> retail gone margin

Sauti/app/src/main/res/layout/fragment_exchange_rate.xml, Sauti/app/src/main/res/layout/item_recent_exchange_rate.xml
=> layout resizing

Sauti/app/src/main/java/com/labs/sauti/adapter/DashboardPagerAdapter.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/DashboardFavoritesFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/DashboardFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/DashboardRecentSearchesFragment.kt, Sauti/app/src/main/res/layout/fragment_dashboard.xml, Sauti/app/src/main/res/layout/fragment_dashboard_favorites.xml, Sauti/app/src/main/res/layout/fragment_dashboard_recent_searches.xml, Sauti/app/src/main/res/values/strings.xml
=> favorites and recent searches viewpager

Sauti/app/src/main/java/com/labs/sauti/api/SautiAfricaApiService.kt, Sauti/app/src/main/java/com/labs/sauti/converter/StringMutableListConverter.kt, Sauti/app/src/main/java/com/labs/sauti/db/SautiRoomDatabase.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/AppModule.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceSearchFragment.kt, Sauti/app/src/main/java/com/labs/sauti/helper/NetworkHelper.kt, Sauti/app/src/main/java/com/labs/sauti/mapper/MarketPriceDataToMarketPriceMapper.kt, Sauti/app/src/main/java/com/labs/sauti/math/LatLon.kt, Sauti/app/src/main/java/com/labs/sauti/model/market_price/MarketPrice.kt, Sauti/app/src/main/java/com/labs/sauti/model/market_price/MarketPriceData.kt, Sauti/app/src/main/java/com/labs/sauti/model/market_price/MarketplaceData.kt, Sauti/app/src/main/java/com/labs/sauti/repository/MarketPriceRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/MarketPriceRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/MarketPriceViewModel.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/market_price/CategoriesViewState.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/market_price/CountriesViewState.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/market_price/MarketsViewState.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/market_price/ProductsViewState.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/market_price/SearchMarketPriceViewState.kt, Sauti/app/src/main/res/layout/fragment_market_price.xml
=> Nearby Marketplace

Sauti/app/src/main/java/com/labs/sauti/adapter/RecentMarketPriceAdapter.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt, Sauti/app/src/main/res/layout/fragment_market_price.xml, Sauti/app/src/main/res/layout/item_recent_market_price.xml
=> recent market prices recycler view

Sauti/app/src/main/java/com/labs/sauti/adapter/RecentExchangeRateConversionResultsAdapter.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRateFragment.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/exchange_rate/RecentConversionResultsViewState.kt, Sauti/app/src/main/res/layout/fragment_exchange_rate.xml, Sauti/app/src/main/res/layout/item_recent_exchange_rate.xml
=> recent conversion results recycler view

Sauti/app/src/main/java/com/labs/sauti/activity/BaseActivity.kt, Sauti/app/src/main/java/com/labs/sauti/api/SautiApiService.kt, Sauti/app/src/main/java/com/labs/sauti/cache/FavoriteExchangeRateConversionCache.kt, Sauti/app/src/main/java/com/labs/sauti/cache/FavoriteExchangeRateConversionRoomCache.kt, Sauti/app/src/main/java/com/labs/sauti/cache/FavoriteMarketPriceSearchCache.kt, Sauti/app/src/main/java/com/labs/sauti/cache/FavoriteMarketPriceSearchRoomCache.kt, Sauti/app/src/main/java/com/labs/sauti/db/FavoriteExchangeRateConversionDao.kt, Sauti/app/src/main/java/com/labs/sauti/db/SautiRoomDatabase.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/DataModule.kt, Sauti/app/src/main/java/com/labs/sauti/di/module/ExchangeRateModule.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRateFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceFragment.kt, Sauti/app/src/main/java/com/labs/sauti/model/exchange_rate/FavoriteExchangeRateConversionData.kt, Sauti/app/src/main/java/com/labs/sauti/repository/ExchangeRateRepository.kt, Sauti/app/src/main/java/com/labs/sauti/repository/ExchangeRateRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/repository/MarketPriceRepositoryImpl.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/ExchangeRateViewModel.kt, Sauti/app/src/main/java/com/labs/sauti/view_state/exchange_rate/IsFavoriteExchangeRateConversionViewState.kt, Sauti/app/src/main/res/drawable/ic_star_empty.xml, Sauti/app/src/main/res/drawable/ic_star_filled.xml, Sauti/app/src/main/res/layout/fragment_exchange_rate.xml, Sauti/app/src/main/res/layout/fragment_market_price.xml
=> Exchange rate favorites

Sauti/app/src/main/java/com/labs/sauti/activity/BaseActivity.kt, Sauti/app/src/main/java/com/labs/sauti/activity/LanguageActivity.kt, Sauti/app/src/main/java/com/labs/sauti/adapter/DashboardFavoritesAdapter.kt, Sauti/app/src/main/java/com/labs/sauti/adapter/RecentExchangeRateConversionResultsAdapter.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRateConvertFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRateFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/HelpFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/MarketPriceSearchFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/ReportFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/SettingsFragment.kt, Sauti/app/src/main/res/layout/fragment_dashboard_favorites.xml, Sauti/app/src/main/res/layout/fragment_dashboard_recent_searches.xml, Sauti/app/src/main/res/layout/fragment_exchange_rate.xml, Sauti/app/src/main/res/layout/fragment_exchange_rate_convert.xml, Sauti/app/src/main/res/layout/fragment_market_price.xml, Sauti/app/src/main/res/menu/activity_main_drawer.xml, Sauti/app/src/main/res/values-lg/strings.xml, Sauti/app/src/main/res/values-sw/strings.xml, Sauti/app/src/main/res/values/strings.xml
=> Translation

Sauti/app/src/main/java/com/labs/sauti/fragment/ExchangeRateFragment.kt, Sauti/app/src/main/res/layout/fragment_dashboard.xml
=> translations on the dashboard added

Sauti/app/build.gradle, Sauti/app/src/main/java/com/labs/sauti/activity/LanguageActivity.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TaxCalculatorFragment.kt, Sauti/app/src/main/java/com/labs/sauti/fragment/TradeInfoFragment.kt, Sauti/app/src/main/java/com/labs/sauti/model/trade_info/TradeInfo.kt, Sauti/app/src/main/java/com/labs/sauti/view_model/TradeInfoViewModel.kt, Sauti/app/src/main/res/layout/fragment_tax_calculator.xml, Sauti/app/src/main/res/values/strings.xml
=> Tax calc fix concurrency

Sauti/.idea/misc.xml, Sauti/app/build.gradle, Sauti/app/src/main/res/values/strings.xml
=> Tax Calc polish
